export default function (serverData = {}) {
    return {
        specialties: serverData.specialties ?? [],
        services: [],
        clinics:[],
        appointments:serverData.appointments ?? [],
        doctors:[],
        stats:serverData.stats ?? [],
        availableSlots:[],
        visiteDate:null,
        currencSection: 1,
        specialitySection: 1,
        serviceSection: 2,
        clinicSection: 3,
        doctorSection: 4,
        dateTimeSection: 5,
        selectedStatus: "all",
        specialtyId: "",
        serviceId: "",
        clinicId: "",
        doctorId: "",
        openSpecialties: false,
        openServices: false,
        selected: {
            specialty: null,
            service: null,
            clinic: null,
            doctor: null,
            date: null,
            slot: null,
        },

        slots: [],
        slotsLoading: false,
        submitting: false,
        showRescheduleModal: false,
        selectedSlot:null,
        currentAppointment:null,
        toast: {
            show: false,
            message: "",
        },
    };
}
