import Alpine from "alpinejs";
import "./clinic/clinicsApp";
import "./clinic/adsApp";
import "./clinic/bookingApp";
import { bookingForm } from "./appointments/booking/booking";
import { vicationForm } from "./vications/vication";
import { doctorsForm } from "./doctors/doctorsForm";
import { schedulesForm } from "./schedules/schedulesForm";
import {clinicServicesForm} from "./clinicServices/clinicServicesForm";
import {subscriptionsForm} from './subscriptions/subscriptionsForm';
import { complaintsForm } from "./complaints/complaintsForm";
window.Alpine = Alpine;
Alpine.data("bookingForm", bookingForm);
Alpine.data("vicationForm",vicationForm);
Alpine.data("doctorsForm",doctorsForm);
Alpine.data("schedulesForm",schedulesForm);
Alpine.data("clinicServicesForm",clinicServicesForm);
Alpine.data("subscriptionsForm",subscriptionsForm);
Alpine.data("complaintsForm",complaintsForm);
Alpine.start();
