export default function (serverData) {
    return {
        clinics: serverData.clinics.data,
        cities: serverData.cities,
        plans: serverData.plans ?? [],
        pagination:serverData.clinics.links ?? [],
        nextId: 5,
        perPage: 10,
        currentPage: 1,
        search: "",
        filterStatus: "",
        filterPlan: "",
        showModal: false,
        showDelete: false,
        showView: false,
        deleteTarget: null,
        viewTarget: null,
        formError: false,
        mode: "add",
        form: {
            name: "",
            email: "",
            city: {
                id:null,
                name:"",
            },
            status: "نشط",
            plan: "Basic",
            address: "",
            owner:{
                id:null,
                name:null,
                user_name:null,
                gendor:null,
            },
            Clinic: null,
            gendor: null,
            phone: null,
            user_name: null,
            password: null,
            plan:{
                id:null,
                name:"",
            },
        },
        toast: {
            show: false,
            msg: "",
            icon: "fa-circle-check",
            bg: "bg-gray-800",
        },
        _toastTimer: null,
    };
}
